In [1]:
function output = addMatrices (A,B);

    dimesions_of_A = size(A);
    dimesions_of_B = size(B);
    
    rows_A = dimesions_of_A(1);
    columns_A = dimesions_of_A(2);
    
    rows_B = dimesions_of_B(1);
    columns_B = dimesions_of_B(2);

    if rows_A ~= rows_B
        disp("rows must match")
        return
    end
    
    if columns_A ~= columns_B
        disp("columns must match")
        return
    end
        
    output = zeros(rows_A, columns_B);
    
    for row = 1:rows_A
        for column = 1:columns_A
            output(row,column) = A(row,column) + B(row,column);
        end
    end
end

Testing the function by adding one to each element on the diagonal of a magic square.

In [2]:
A = eye(4)
B = magic(4)
addMatrices(A,B)

A =

Diagonal Matrix

   1   0   0   0
   0   1   0   0
   0   0   1   0
   0   0   0   1

B =

   16    2    3   13
    5   11   10    8
    9    7    6   12
    4   14   15    1

ans =

   17    2    3   13
    5   12   10    8
    9    7    7   12
    4   14   15    2



Tesing function with incompatible matrices.

In [3]:
C = ones(2)
D = magic(3)
addMatrices(C,D)

C =

   1   1
   1   1

D =

   8   1   6
   3   5   7
   4   9   2

rows must match
