# Adding Matrices - Hints

## Overview:
- **Teaching:** 5 min
- **Exercises:** 10 min

**Questions**
- What MATLAB functions will be useful in coding matrix addition?

**Objectives**
- understand how to use the `size` function
- be able to use nested `for` loops
- remember how to declare a `function`
- remember how to test for equality `==`
- use the `zeros` function to store answers
- read pseudocode

### Size function

We must first be able to find out the size of a given matrix. The `size` command is useful for this. Consider the following example.

In [1]:
X = [1:5 ; 6:10]
dimesions = size(X)
rows = dimesions(1)
columns = dimesions(2)

X =

    1    2    3    4    5
    6    7    8    9   10

dimesions =

   2   5

rows =  2
columns =  5


## Information: size function
`size(M)` returns a matrix `[r,c]` containing the number of rows, r, and the number of columns, c, of matrix `M`.

### For loop recap

We also need to be able to loop through elements in a matrix to add each element together. Using the Matrix `X` and the variable rows as defined earlier we can use a `for` loop to loop through the rows of `X`. Remeber `X(1,:)` returns the first row of matrix `X`.

In [2]:
for row = 1:rows
    printf("Row %d is: ", row)
    X(row,:)
end

Row 1 is: ans =

   1   2   3   4   5

Row 2 is: ans =

    6    7    8    9   10



To cycle through each element in the `X` we can use nested `for` loops. Nested `for` loops are loops inside other loops. Consider the following example again about matrix `X`.

In [3]:
for row = 1:rows
    for column = 1:columns
        printf("Element from row %d, column %d ", row, column)%note in MATLAB this function is called fprintf
        X(row,column)
    end
end

Element from row 1, column 1 ans =  1
Element from row 1, column 2 ans =  2
Element from row 1, column 3 ans =  3
Element from row 1, column 4 ans =  4
Element from row 1, column 5 ans =  5
Element from row 2, column 1 ans =  6
Element from row 2, column 2 ans =  7
Element from row 2, column 3 ans =  8
Element from row 2, column 4 ans =  9
Element from row 2, column 5 ans =  10


### Information: For loops
A `for` loop repeats a set of instructions for each element in an array.

### Checking for equality
Next is a little reminder on how we can check if two quantities are equal.

In [4]:
rows = 2

if rows == 2
    disp("This code will get executed")
end

if rows != 2 % not equal is written as ~= in MATLAB
    disp("This code won't get executed")
end

rows =  2
This code will get executed


### Information: Equality
Remember `=` is used to assign a value to a variable. `==` is used to check if two things are equal.

### zeros function
It is often useful to have somewhere to store answers. We can do this by creating a matrix full of zeros using the `zeros` function. For example:

In [5]:
zeros(2,3)

ans =

   0   0   0
   0   0   0



### Information: zeros function
It is often useful to create a place to store your answers, `zeros(n,m)` will create an `n` by `m` array of zeros.

### Defining functions
Finally we'll need to wrap all this stuff into a `function`. When you define a function you define the functions inputs and outputs. Remember that the variable names inside the function are local to it and won't interfere with variables of the same name outside the function.

In [6]:
function output = getMatrixRows (matrix);
    dimesions = size(matrix);
    rows = dimesions(1);
    output = rows;
end

M = magic(4)
disp("The number of rows in M is...")
getMatrixRows(M)

M =

   16    2    3   13
    5   11   10    8
    9    7    6   12
    4   14   15    1

The number of rows in M is...
ans =  4


### Information: function declaration
Remember that a function only has access to the variables that are passed into it. Also, the variable names used inside the function can be the same as variable names outside the function - each function has its own name space.

## Exercise: Create the adding matrices funciton
Finally all of these elements are going to be drawn together to make the whole function. I have given an outline of the function in psuedocode (Psuedocode is easily readible 'almost code' that makes writing the final program easier). Convert the psuedocode into realcode!:
```
function answer = addMatrices(A,B)

rows_A
rows_B
columns_A
columns_B

answer = empty matrix to store answers

if rows in A and B are not equal
    print matrices must have the smae number of rows
end

if columns in A and B are not equal
    print matrices must have the same number of columns
end

for row in rows
    for column in columns
        answer(row,column) = A(row,column) + B(row,column)
    end
end

end

```

[Solution](03_adding_matrices_hints-soln.ipynb)

## Key Points:
- `size` can be used to get the dimesions of a matrix
- `for` loops can be placed inside each other
- `==` can be used to check equality
- `~=` is for not equal