# Multiplying Matrices - Solution

In [1]:
function output = multiMatrices (A,B);

    dimesions_of_A = size(A);
    dimesions_of_B = size(B);
    
    rows_A = dimesions_of_A(1);
    columns_A = dimesions_of_A(2);
    
    rows_B = dimesions_of_B(1);
    columns_B = dimesions_of_B(2);

    if columns_A ~= rows_B
        disp("dimension mismatch")
        return
    end
    
    output = zeros(rows_A, columns_B);
    
    for rowA = 1:rows_A
        for columnB = 1:columns_B
            for rowB = 1:rows_B
                output(rowA,columnB) = output(rowA,columnB) + A(rowA,rowB) * B(rowB,columnB);
            end
        end
    end
end

Testing the function: The identity matrix mulitplied by another matrix should just return the other matrix

In [2]:
I = eye(3)
M = magic(3)
multiMatrices(I,M) %this should give M back

I =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   1

M =

   8   1   6
   3   5   7
   4   9   2

ans =

   8   1   6
   3   5   7
   4   9   2



Testing the function with two mismatched matrices.

In [3]:
A = 1:10
B = magic(3)
multiMatrices(A,B)

A =

    1    2    3    4    5    6    7    8    9   10

B =

   8   1   6
   3   5   7
   4   9   2

dimension mismatch


Testing the function with non-square matrices.

In [4]:
C = [1 2 3; 4 5 6]
D = [7 8; 9 10; 11 12]
multiMatrices(C,D)

C =

   1   2   3
   4   5   6

D =

    7    8
    9   10
   11   12

ans =

    58    64
   139   154



## Key Points:
- Good luck creating your programs